package com.semperti.aleman.bpm.bpmreintegros;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AutorizacionReintegro implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Autorizo Reintegro")
   private java.lang.Boolean autorizoReintegro;
   @org.kie.api.definition.type.Label(value = "Comentario")
   private java.lang.String comentario;

   public AutorizacionReintegro()
   {
   }

   public java.lang.Boolean getAutorizoReintegro()
   {
      return this.autorizoReintegro;
   }

   public void setAutorizoReintegro(java.lang.Boolean autorizoReintegro)
   {
      this.autorizoReintegro = autorizoReintegro;
   }

   public java.lang.String getComentario()
   {
      return this.comentario;
   }

   public void setComentario(java.lang.String comentario)
   {
      this.comentario = comentario;
   }

   public AutorizacionReintegro(java.lang.Boolean autorizoReintegro,
         java.lang.String comentario)
   {
      this.autorizoReintegro = autorizoReintegro;
      this.comentario = comentario;
   }

   public String toString() {
       return "[ AutorizacionReintegro: " + (autorizoReintegro != null && autorizoReintegro ? "autorizada" : "rechazada") + " comentario: '"+comentario+"' ]";
   }
}