package com.semperti.aleman.bpm.bpmreintegros;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Paciente implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Paciente() {
    }

}